spring:
  datasource:
    username: root
    password: 357932511
    url: jdbc:mysql://localhost:3306/zlcz_test?useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml